global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "tp15-spring-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8080"]
    scrape_interval: 5s
    labels:
      application: "tp15-monitoring"
      environment: "development"
      tp: "15"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]